Memory.create!([
  {title: "You’re a wizard, Harry.", content: "I'm a what? gasped Harry.\r\nA wizard, o' course, said Hagrid, sitting back down on the sofa, which groaned and sank even lower, \"an' a thumpin' good'un I'd say, once yeh've been trained up a bit. With a mum an' dad like yours, what else would yeh be?\r\n― J.K. Rowling, Harry Potter and the Sorcerer's Stone", user_id: 1},
  {title: "You’re a little scary sometimes, you know that?", content: "Neville Longbottom: You’re sneaking out again, aren’t you?\r\nHarry Potter: Now, Neville, listen. We were…\r\nNeville Longbottom: No, I won’t let you! You’ll get Gryffindor into trouble again. I’ll fight you. (raises his fists)\r\nHermione Granger: Neville, I’m really really sorry about this. Petrificus Totalus.\r\n(Neville's arms snap to his sides, and he drops to the floor, frozen stiff as a board) \r\nRon Weasley: You’re a little scary sometimes, you know that? Brilliant, but scary.\r\n— Harry Potter and the Sorcerer's Stone", user_id: 1},
  {title: "You're just as sane as I am.", content: "Harry Potter: What is it?\r\n(sees a strange reptilian-like horse)\r\nRon Weasley: What's what?\r\nHarry Potter: That. Pulling the carriage.\r\nHermione Granger: Nothing's pulling the carriage, Harry. It's pulling itself like always.\r\n(Harry walks around the carriage, where Luna is already seated)\r\nLuna Lovegood: You're not going mad.\r\n(lowers her magazine, The Quibbler, which she has been reading upside down)\r\nLuna Lovegood: I see them too. You're just as sane as I am.\r\n― J.K. Rowling, Harry Potter and the Order of the Phoenix", user_id: 1},
  {title: "We’ve all got both light and dark inside us.", content: "The world isn’t split into good people and Death Eaters. We’ve all got both light and dark inside us. What matters is the part we choose to act on. That's who we really are.\r\n― J.K. Rowling, Harry Potter and the Order of the Phoenix", user_id: 1},
  {title: "No post on Sundays.", content: "Vernon Dursley: Fine day, Sunday. In my opinion, best day of the week. Why is that, Dudley?\r\nHarry Potter: Because there’s no post on Sundays?\r\nVernon Dursley: Right you are, Harry! No post on Sunday. No blasted letters today! No, sir. Not one single bloody letter. Not one! No, sir, not one blasted, miserable… \r\n(gets hit with a letter flying out of the fireplace)\r\n― J.K. Rowling, Harry Potter and the Sorcerer's Stone", user_id: 1},
  {title: "After all this time? Always.\"", content: "But this is touching, Severus, said Dumbledore seriously. Have you grown to care for the boy, after all?\r\nFor him? shouted Snape. Expecto Patronum!\r\nFrom the tip of his wand burst the silver doe. She landed on the office floor, bounded once across the office, and soared out of the window. Dumbledore watched her fly away, and as her silvery glow faded he turned back to Snape, and his eyes were full of tears.\r\nAfter all this time?\r\nAlways,” said Snape.\r\n― J.K. Rowling, Harry Potter and the Deathly Hallows", user_id: 1},
  {title: "Don’t you dare call Hagrid pathetic you foul—you evil...", content: "Have you ever seen anything quite as pathetic?\" said Malfoy. \"And he’s supposed to be our teacher!\r\nHarry and Ron both made furious moves toward Malfoy, but Hermione got there first - (SMACK!)\r\nShe had slapped Malfoy across the face with all the strength she could muster. Malfoy staggered. Harry, Ron, Crabbe, and Goyle stood flabbergasted as Hermione raised her hand again.\r\nDon’t you dare call Hagrid pathetic you foul—you evil...\r\nHermione!\" said Ron weakly and he tried to grab her hand as she swung it back.\r\nGet off Ron!\r\nHermione pulled out her wand. Malfoy stepped backward. Crabbe and Goyle looked at him for instructions, thoroughly bewildered.\r\nC’mon, Malfoy muttered, and in a moment, all three of them had disappeared into the passageway to the dungeons.\r\nHermione!\" Ron said again, sounding both stunned and impressed.\r\n― J.K. Rowling, Harry Potter and the Prisoner of Azkaban", user_id: 1},
  {title: "There are all kinds of courage.", content: "There are all kinds of courage, said Dumbledore, smiling. It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.\r\n― J.K. Rowling, Harry Potter and the Sorcerer's Stone", user_id: 1},
  {title: "We could all have been killed — or worse, expelled.", content: "I hope you're pleased with yourselves. We could all have been killed — or worse, expelled. Now if you don't mind, I'm going to bed.\r\n― J.K. Rowling, Harry Potter and the Sorcerer's Stone", user_id: 1},
  {title: "happiness can be found even in the darkest of times", content: "Dumbledore: A word of caution, dementors are vicious creatures. They will not distinguish between the one they hunt and the one who gets in their way. Therefore I must warn each and every one of you to give them no reason to harm you. It's not in the nature of a dementor to be forgiving. But you know happiness can be found even in the darkest of times, when one only remembers to turn on the light.\r\n― Harry Potter and the Prisoner of Azkaban", user_id: 1},
  {title: "It's wingardium leviOsa, not leviosAH.", content: "Wingardium Leviosa! he shouted, waving his long arms like a windmill.\r\nYou're saying it wrong,' Harry heard Hermione snap. 'It's Wing-gar-dium Levi-o-sa, make the \"gar\" nice and long.\r\nYou do it, then, if you're so clever' Ron snarled.\r\nHermione rolled up the sleeves of her gown, flicked her wand and said, Wingardium Leviosa!\r\n(Their feather rose off the desk and hovered about four feet above their heads)\r\n― J.K. Rowling, Harry Potter and the Sorcerer's Stone", user_id: 1}
])

Emotion.create!([
  {name: "hopeful"},
  {name: "curious"},
  {name: "surprise"},
  {name: "awe"},
  {name: "love"},
  {name: "respect"},
  {name: "fear"},
  {name: "admiration"},
  {name: "joyful"},
  {name: "remorse"},
  {name: "entertained"},
  {name: "pride"},
  {name: "annoyed"},
  {name: "anger"},
  {name: "tired"},
  {name: "stoked"},
  {name: "happy"},
  {name: "excited"},
  {name: "lovey"},
  {name: "glad"},
  {name: "sadness"}
])

Player.create!([
  {name: "me, myself, and I"},
  {name: "cheeby cheepkins"},
  {name: "Harry Potter"},
  {name: "Rubeus Hagrid"},
  {name: "Albus Dumbledore"},
  {name: "Severus Snape"},
  {name: "Luna Lovegood"},
  {name: "Ron Weasley"},
  {name: "Hermione Granger"},
  {name: "Sirius Black"},
  {name: "Vernon Dursley"},
  {name: "Severus Snape's Patronus Of A Doe"},
  {name: "Draco Malfoy "},
  {name: "Vincent Crabbe"},
  {name: "Gregory Goyle"},
  {name: "Neville Longbottom"},
  {name: "Dudley Dursley"},
  {name: "Petunia Dursley"},
  {name: "kitty bear"},
  {name: "Me"},
  {name: "mat"},
  {name: "dren king"},
  {name: "me"},
  {name: "wookie"}
])

MemoryPlayer.create!([
  {memory_id: 1, player_id: 3},
  {memory_id: 1, player_id: 4},
  {memory_id: 3, player_id: 7},
  {memory_id: 3, player_id: 3},
  {memory_id: 2, player_id: 8},
  {memory_id: 2, player_id: 9},
  {memory_id: 2, player_id: 3},
  {memory_id: 4, player_id: 10},
  {memory_id: 4, player_id: 3},
  {memory_id: 5, player_id: 11},
  {memory_id: 5, player_id: 3},
  {memory_id: 6, player_id: 6},
  {memory_id: 6, player_id: 5},
  {memory_id: 6, player_id: 12},
  {memory_id: 7, player_id: 9},
  {memory_id: 7, player_id: 3},
  {memory_id: 7, player_id: 8},
  {memory_id: 7, player_id: 13},
  {memory_id: 7, player_id: 14},
  {memory_id: 7, player_id: 15},
  {memory_id: 11, player_id: 9},
  {memory_id: 11, player_id: 3},
  {memory_id: 11, player_id: 8},
  {memory_id: 11, player_id: 16},
  {memory_id: 5, player_id: 17},
  {memory_id: 5, player_id: 18},
  {memory_id: 8, player_id: 16},
  {memory_id: 8, player_id: 3},
  {memory_id: 8, player_id: 8},
  {memory_id: 8, player_id: 9},
  {memory_id: 8, player_id: 5},
  {memory_id: 9, player_id: 9},
  {memory_id: 9, player_id: 3},
  {memory_id: 9, player_id: 8},
  {memory_id: 1, player_id: 11},
  {memory_id: 1, player_id: 17},
  {memory_id: 1, player_id: 18},
  {memory_id: 10, player_id: 3},
  {memory_id: 10, player_id: 5},
  {memory_id: 22, player_id: 24}
])

MemoryEmotion.create!([
  {memory_id: 1, emotion_id: 3},
  {memory_id: 2, emotion_id: 3},
  {memory_id: 2, emotion_id: 7},
  {memory_id: 2, emotion_id: 8},
  {memory_id: 4, emotion_id: 9},
  {memory_id: 5, emotion_id: 10},
  {memory_id: 6, emotion_id: 11},
  {memory_id: 7, emotion_id: 3},
  {memory_id: 6, emotion_id: 3},
  {memory_id: 6, emotion_id: 9},
  {memory_id: 7, emotion_id: 8},
  {memory_id: 7, emotion_id: 12},
  {memory_id: 11, emotion_id: 3},
  {memory_id: 8, emotion_id: 3},
  {memory_id: 8, emotion_id: 10},
  {memory_id: 8, emotion_id: 13},
  {memory_id: 9, emotion_id: 14},
  {memory_id: 9, emotion_id: 15},
  {memory_id: 9, emotion_id: 7},
  {memory_id: 10, emotion_id: 4},
  {memory_id: 4, emotion_id: 16},
  {memory_id: 6, emotion_id: 5},
  {memory_id: 4, emotion_id: 5},
  {memory_id: 14, emotion_id: 18},
  {memory_id: 6, emotion_id: 24}
])

puts "After seeding the database: "
puts " - There are #{Memory.count} memories."
puts " - There are #{Emotion.count} emotions."
puts " - There are #{Player.count} people and/or pets."
